### ISSUE TITLE
Grunt Exec Command with subdirectory path not working on windows

### ISSUE THREAD

**Issue by p0wl** [jharding/grunt-exec#32]
I have the following command to execute using grunt (exec):

`command: './node_modules/.bin/component install'`

The grunt tasks fails with the following error:

![image](https://f.cloud.github.com/assets/596578/1427336/b3f56c42-4087-11e3-8501-cabbe5dd2d05.png)

If i execute the command in cmd (or powershell) it is working.

![image](https://f.cloud.github.com/assets/596578/1427348/e4758532-4087-11e3-9eef-ac8759419ccc.png)

any idea? it doesn't matter if the command uses / oder \

Thanks in advance.

**Comment by mcandre** [comment]
Could grunt-exec automatically perform `path.relative` translation on the first whitespace-separated token in tasks? That way, Grunt "just works" on more operating systems.

**Comment by gwicksted** [comment]
It could do this.. but then it would break in other situations (ie if "node" were specified before the path).  grunt-exec has no way of knowing what is a path and what is an executable or argument.  This is up to the user.
