### ISSUE TITLE
Can't use 'source' to run a bash script

### ISSUE THREAD

**Issue by blakewest** [jharding/grunt-exec#36]
Hi, I'm trying to use this to automate the running of a bash script that sets environment variables in my project. If I just personally run the command 'source ./my_script.sh' then it works just fine. But if I put that same command into grunt-exec, it says that it runs without errors, but the vars aren't actually set. 

Any thoughts on what the issue is? 

Thanks! - Blake

**Comment by kevinSuttle** [comment]
I think this is an issue with Node in general, isn't it?

**Comment by gwicksted** [comment]
Yes, this is not a grunt-exec issue nor a Grunt issue nor a NodeJS issue.  It is a limitation of processes/subprocesses and env var handling.

Options:
1) echo each environment variable (with delimiters) to stdout and parse them with the callback method.  

2) Or output a file that you can parse from within grunt.

3) Define the env vars before calling grunt.

4) Spawn a second grunt process immediately following your existing command (in the same grunt-exec call) and specify only the task(s) that require those env vars to be set.  You can access them within grunt via `process.env.ENV_VARIABLE` or pass them into grunt as args via `--argname=value` and retrieving them via `grunt.option('argname')`
