### ISSUE TITLE
Please use grunt.util.spawn

### ISSUE THREAD

**Issue by stevenvachon** [jharding/grunt-exec#46]
It uses `child_process.spawn()` which preserves stdout/stderr colors.

If you'd rather use Node's API directly, here's how I'm currently doing it:

``` javascript
var child = child_process.spawn(app, [command], {cwd:cwd, stdio:"inherit"});

child.on("exit", function(code)
{
    this.removeAllListeners();

    callback();
});
```

**Comment by gwicksted** [comment]
Upcoming version using child_process.spawn instead of child_process.exec.
