### ISSUE TITLE
Can't interact with commands ran (stdin broken)

### ISSUE THREAD

**Issue by drewzh** [jharding/grunt-exec#52]
When I execute a command, in my case `cordova build android --release`, that prompts me to enter the password to unlock my signing key, I can enter text but when I hit return I just get a new line and the input doesn't propagate the command in progress, halting the script execution. I've checked the readme and closed issues but can't find anything related to a solution to this?

Thanks

**Comment by lipsumar** [comment]
I found a solution, i'll do a pull request very soon.

**Comment by dustball** [comment]
I also desired this functionality.  Grunt is great, by the way.

**Comment by lipsumar** [comment]
https://github.com/jharding/grunt-exec/pull/62

**Comment by gwicksted** [comment]
Merged PR
