### ISSUE TITLE
Creates only invalid links

### ISSUE THREAD

**Issue by AntonTrapp** [jharding/grunt-exec#53]
absolute (like here) or relative:

    symlink:
      bower_components:
        target: 'bower_components'
        link: '/Users/atrapp/development/sentialfive/public/bower_components'

creates only bower_components -> bower_components link which is pretty useless ;)

**Comment by cvrebert** [comment]
I think you reported this to the wrong project. Perhaps you meant https://github.com/gruntjs/grunt-contrib-symlink instead?

**Comment by AntonTrapp** [comment]
Could be, long time ago...

**Comment by gwicksted** [comment]
Sorry this is the incorrect project.  Closing...
