### ISSUE TITLE
INT signal is trapped away from spawned process

### ISSUE THREAD

**Issue by dandv** [jharding/grunt-exec#57]
Same as [grunt-spawn](https://github.com/fir3pho3nixx/grunt-spawn/issues/6) and grunt-shell (couldn't post the issue there because the author is [a bit of a dick](http://imgur.com/Qwb7bOr)).

Steps to reproduce:

```sh
git clone git@github.com:MeteorPackaging/summernote.git
cd summernote
git checkout meteor-integration
npm install
grunt meteor-test
```

This uses `grunt-exec` (replace "shell" in the [source lines](https://github.com/MeteorPackaging/summernote/blob/meteor-integration/Gruntfile.js#L109-117)) to execute `meteor/runtests/sh`, which [traps the INT signal](https://github.com/MeteorPackaging/summernote/blob/meteor-integration/meteor/runtests.sh#L11-16).

Now press Ctrl+C.

Notice that grunt aborts instantly, without giving `runtests.sh` a chance to trap the INT signal and do its cleanup.

**Comment by gwicksted** [comment]
It appears grunt-spawn resolved this issue by using grunt.util.spawn which is #46.  Closing as a dup.
