### ISSUE TITLE
Colorful output

### ISSUE THREAD

**Issue by nonlux** [jharding/grunt-exec#59]
I use this plugin with watch plugin for autostart tests.
How can I see colroful output from my script under `exec:test` task ?

**Comment by nonlux** [comment]
Sorry, color works fine!
[Solution](http://stackoverflow.com/questions/18825493/retaining-output-colors-when-shelling-out-to-node?answertab=active#tab-top)

**Comment by Dremora** [comment]
Still an issue in my case since the command I'm trying to execute doesn't have any flags to enable colors.

**Comment by dickeylth** [comment]
+1 with @Dremora

**Comment by gwicksted** [comment]
@Dremora and @dickeylth can you detail what the command is you are executing and what output is displayed + what you expected for color highlighting?

Also, have you tried this type of configuration (the `stdout: 'inherit'` is the important part):

```js
module.exports = function(grunt) {
  grunt.initConfig({
    exec: {
      something: {
        command: process.platform === 'win32' ? 'dir' : 'ls -la'
      , stdout: 'inherit'
      , stderr: 'inherit'
      }
    }
  });
};
```

**Comment by dickeylth** [comment]
@gwicksted I've created a very simple demo: https://github.com/dickeylth/grunt-exec-issue, you can check out and debug.

**Comment by gwicksted** [comment]
I have reproduced the issue and implemented a fix - it is a major change due to the capabilities of child_process.exec.  The next release (2.0.0) will contain this capability.

**Comment by gwicksted** [comment]
Please try `grunt-exec@2.0.0-alpha.0` aka `grunt-exec@next` for the new behavior.  `grunt-exec@latest` is still the stable `1.0.1` release.  One of the tests is failing so I'm looking into it but things are otherwise stable.

**Comment by dickeylth** [comment]
@gwicksted I've updated and retried, and unfortunately it still won't work:

![](https://img.alicdn.com/tfs/TB1RBx.PXXXXXbOaXXXXXXXXXXX-588-436.png)

**Comment by gwicksted** [comment]
Hi @dickeylth , please try with the stdout: 'inherit' option.  Example change to your grunt file: https://github.com/gwicksted/grunt-exec-issue/tree/patch-1

**Comment by gwicksted** [comment]
`grunt-exec@2.0.0-alpha.2` (aka `grunt-exec@next`) now supports the shortcut option `stdio: 'inherit'`

**Comment by dickeylth** [comment]
@gwicksted Unfortunately it still won't work, I've updated my [Gruntifile.js](https://github.com/dickeylth/grunt-exec-issue/blob/master/Gruntfile.js#L14)

**Comment by dickeylth** [comment]
@gwicksted It worked now, thank you!

**Comment by dickeylth** [comment]
@gwicksted I'm wondering when would the `grunt-exec@next` be released?

**Comment by gwicksted** [comment]
@dickeylth I was holding back the release a bit because it replaces the entire back-end of grunt-exec.  That said, I've been using this version since Jan with no issues so I think it's safe to mark it stable.
