### ISSUE TITLE
Use a function to set the cwd

### ISSUE THREAD

**Issue by jlogar** [jharding/grunt-exec#65]
The cwd is sometimes not known until execution time. It would be nice to be able to set it from a function. Something like:
```
grunt.initConfig({
  exec: {
    sample: {
      command: {...},
      cwd: function() {
        return "/my/dynamicpath";
      }
    }
  }
});
```

Would a pull request for something like that be merged into grunt-exec?

**Comment by theaccordance** [comment]
You can achieve this without modifying the plugin by leveraging grunt's template strings in your config object, that's how I handle dynamic configurations before tasks are run

**Comment by jlogar** [comment]
not really using grunt anymore. thanks anyway!
