### ISSUE TITLE
Do not execute Multiple cmd

### ISSUE THREAD

**Issue by manigandaprabu** [jharding/grunt-exec#66]
exec: {
              echo_something: 'echo "This is something"',
              cmd: 'lessc --source-map=main.map less/main.less css/main.css',
              cmd: 'lessc --source-map=file2.map less/file2.less css/file2.css'
              },
which execute last cmd only

**Comment by JamilHijjawi** [comment]
Use && between the commands in the same line

exec: {
cmd: 'lessc --source-map=main.map less/main.less css/main.css && lessc --source-map=file2.map less/file2.less css/file2.css'
},

**Comment by gwicksted** [comment]
Closing but will enhance documentation to address this.

**Comment by cobbdb** [comment]
Would be very nice if cmd also accepted a set of commands:
```
mytask: {
    cmd: [
        'echo first',
        'echo second'
    ]
}
```

**Comment by gwicksted** [comment]
@cobbdb I'll look into adding this.  In the meantime, you can have multiple named tasks under exec or concatenate them together as demonstrated above.

**Comment by cobbdb** [comment]
Just saw comment in #73..  so simple love it. For others searching, here is my example from above updated to work for current version:
```
mytask: {
    cmd: [
        'echo first',
        'echo second'
    ].join('&&')
}
```

**Comment by importerror** [comment]
Direct execution of the multiple commands:
`mytask: [
    'echo first',
    'echo second'
]`
