### ISSUE TITLE
If child is killed, task output should show the kill signal, not 'exited with 0'

### ISSUE THREAD

**Issue by jonnor** [jharding/grunt-exec#67]
For instance when maxBuffer is exceeded (ref #64), the parent process (grunt) will kill the child.
In this case `code` is `null`, and the second argument of (`signal`) is set. However the logic in the task does not check signal, and instead prints (the very confusing) message:

```
Exited with code: 0.
Warning: Task "exec:dockerNode" failed. Use --force to continue.

Aborted due to warnings.
```

https://github.com/jharding/grunt-exec/blob/master/tasks/exec.js#L65

**Comment by gwicksted** [comment]
Merged into new ticket #71
