### ISSUE TITLE
Command working on shell but not with grunt-exec

### ISSUE THREAD

**Issue by ali-faizan** [jharding/grunt-exec#69]
I am trying to create mysql database using grunt task and following command.

mysql -u "${DB_USER}" -p"${DB_PASSWORD}"  -e "CREATE DATABASE IF NOT EXISTS \`${DATABASE}\`;"

The database name have dash(-) in it so i have to put "`" before name, escaped with "\" which cannot be seen here. This works when I run it on shell directly. 

But when running with grunt, i am getting following error:
> /bin/sh: 1:
> test-db: not found
> ERROR
> 1064 (42000)
> at line 1
> : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
> Exited with code: 1.
Warning: Task "exec:create_database" failed. Use --force to continue.

**Comment by gwicksted** [comment]
I assume you're using ES6 template strings to fill in the variables so I created a test below that outputs the expected string.

Looks like MySQL might be getting a double-quote inside the query causing the error you mentioned.  Perhaps you have an escaped double-quote in your command or your user/password/database have values that require further escaping?

```js
    // within "exec:" task
    test_mysql_ticket: {
      cmd: function () {
        var DB_USER = "abc";
        var DB_PASSWORD = "password";
        var DATABASE = "database-with-dashes";
        return `echo mysql -u "${DB_USER}" -p"${DB_PASSWORD}" -e "CREATE DATABASE IF NOT EXISTS \`${DATABASE}\`;"`;
      },
      callback: function(err, stdout, stderr) {
        console.log('stdout: ' + stdout);
        if ((stdout + "").trim() !== 'mysql -u "abc" -p"password" -e "CREATE DATABASE IF NOT EXISTS `database-with-dashes`;"') {
          grunt.log.error("Unexpected result: " + stdout);
          return false;
        }
      }
    }

```

**Comment by gwicksted** [comment]
Could not reproduce
