### ISSUE TITLE
Better error message when exceeding maxBuffer size

### ISSUE THREAD

**Issue by gwicksted** [jharding/grunt-exec#71]
See #64 and #67

**Comment by kaynz** [comment]
Is there any workaround for this problem in 0.4.7?

**Comment by gwicksted** [comment]
Hi @kaynz , you probably don't want `Infinity` since this is a memory limit value for stderr/stdout coming from the child process and you probably don't want to soak up all the memory on your system if something goes awry.  The default (front NodeJS) is a respectable 200KB - if this is not enough, you may be better off piping it elsewhere (a file).  I'm going to be looking at these options in more detail soon -- do you have a specific use case I can verify against while testing?

**Comment by kaynz** [comment]
Hi,
thanks for your quick response. I'm using grunt-exec for cordova build process automation. Especially the ios build process (cordova build ios --device) runs into the maxBuffer of 200kb.

**Comment by gwicksted** [comment]
You could try adding `-ll error` (log level) to the end of your `cordova build` command.  If that doesn't do it, try increasing the `maxBuffer` of grunt exec to something like `500*1024`.  Are you using `bash`?  If so you might be able to append this to the end: ` >| tee build.log` which should overwrite `build.log` each time with the `stdout` from `cordova` as well as suppressing it from the child process stdout stream (untested).

**Comment by gwicksted** [comment]
Large maxBuffer sizes have been tested, better error handling added.
