### ISSUE TITLE
Unix combine commands with && does not work

### ISSUE THREAD

**Issue by Kasheftin** [jharding/grunt-exec#79]
That's my typical config I use for years:

    config.exec: {
      sources: {
        cmd: 
          "mkdir build/fonts/bootstrap"+
          " && "
          "cp -r vendor/bootstrap-sass/assets/fonts/bootstrap/* build/fonts/bootstrap"+
          " && "
          ...
       }
    }

It works fine with 1.0.1. It does not work with 2.0.0.

**Comment by gwicksted** [comment]
I'll fire up a Linux VM and test.  Can you send me the error message?  The following is working for me in Windows:

```js
test_multiple_commands: {
      cmd: 
        process.platform === "win32" ? 
              "(rmdir /s /q build || echo 'no build dir')" +
              " && " +
              "mkdir build" +
              " && " +
              "copy * build" +
              " && " +
              "echo done"
            : "rm -rf build" +
              " && " +
              "cp * build" +
              " && " +
              "echo done"
    }
```

**Comment by Kasheftin** [comment]
Anything with && works incorrect (and with ; as well). For example, `echo 1 && echo 2` should output 1 and 2.
That's the exact code:

    module.exports = function(grunt) {
      config.exec = {
        test: {
          cmd: "echo 1 && echo 2"
        }
      }
      grunt.initConfig(config);
      grunt.loadNpmTasks("grunt-exec");
      grunt.registerTask("test",["exec:test"]);
    }

There's splitArgs function, it count everything after the first space as command argument. That's the `grunt test --verbose` result:

    Running "exec:test" (exec) task
    Verifying property exec.test exists in config...OK
    File: [no files]    

    echo 1 && echo 2
    buffer   : disabled
    timeout  : infinite
    killSig  : SIGTERM
    shell    : true
    command  : echo
    args     : [1,&&,echo,2]
    stdio    : [ignore,pipe,pipe]
    cwd      : /home/www/obzor/html/tools
    exitcodes: 0
    pid     : 23072
    >> Exited with code: 0.
    1 && echo 2

So the result is `1 && echo 2` - everything after the first space counts as the first echo's command argument.

**Comment by kiyanwang** [comment]
having the same problem as @Kasheftin  any thoughts on how to resolve this?

**Comment by gwicksted** [comment]
Fixed. Please retry with `grunt-exec` `3.0.0` (bumped major due to possibly breaking changes relying on incorrect quote/space handling of v2 on non-win32).
