### ISSUE TITLE
Redirecting command output to a file does not work ( using >> or > )

### ISSUE THREAD

**Issue by mshahidkhan** [jharding/grunt-exec#82]
grunt-exec works fine to me.
I wanted to have some command output redirected to a file
```
cmd: function(filename) {
                filename = filename || 'someLog.txt';
                return 'ls -l >> ' + filename ; }
```
when I do the above, I still get output on terminal. 
Technically, it's not an issue but could be a good enhancement.
Thanks!

**Comment by gwicksted** [comment]
Fixed. Please retry with `grunt-exec` `3.0.0` (bumped major due to possibly breaking changes relying on incorrect quote/space handling of v2 on non-win32).
