### ISSUE TITLE
rsync with sshpass

### ISSUE THREAD

**Issue by pedrosmmc** [jharding/grunt-exec#86]
Doesn't exec the rsync with sshpass:

```
  exec: {
     'synco-stage': {
        command: 'rsync -aAHP --rsh="sshpass -p p3dr079 ssh -o StrictHostKeyChecking=no -l pedrocoelho" html/ pedrocoelho@192.168.1.36:/var/www/pedrocoelho.net/html/'
      }
  }
```

same command on bash execute perfectly!!!
some help here please!

**Comment by gwicksted** [comment]
What is output?  You're welcome to browse the code and hint at an area that requires a change or submit a PR.  I don't have as much time dedicated to `grunt-exec` as I did in the past.

From a security perspective: I highly recommend **not** using `sshpass` with the `-p` option especially in a multi-user environment (no matter where it's executed from).  Instead, if possible, use key-based authentication and create an entry in `~/.ssh/config` specifying `Host`, `HostName`, `Port`, `User`, and most importantly `IdentityFile` pointing to the `.key` file.  Then invoke rsync without sshpass and it will pick up and submit the appropriate key based on the host.
